### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rdshft** [redshifttt/spiderlinux#2]
Currently the distro is in a state where we could easily get a bootable image up and running. Here is the roadmap I suggest:

- [x] Python rewrite of the build scripts
- [ ] Toolchain
    - [ ] Basic Utilities (shell etc)
- [x] Pick an Init System (openrc)
- [ ] Kernel Config
- [ ] Create image for booting
- [ ] Make a start on Arachnid
- [ ] Move away from build scripts and use arachnid

Using python for the new build scripts because it's a lot more flexible than shell and that's what we've needed for a while.

**Comment by redshifttt** [comment]
Picked runit as the init system for the time being. Looking at dinit

**Comment by redshifttt** [comment]
Dinit is the new init system pick. Will test the system with it then move from there
